__author__ = 'adrian'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
'''
fib_first = 1
fib_second = 2
fib_sum = 2
while fib_second <= 4000000:
	prev_second = fib_second
	fib_second += fib_first
	fib_first = prev_second
	if (fib_second % 2) is 0:
		fib_sum += fib_second

print fib_sum
